export const projects = [
  {
    name: "Pancratia Hall Lofts",
    img: "/images/pancratia/pancratia-hero-cropped.jpg",
    type: "redevelopment",
    link: "/redevelopment/pancratia-hall-lofts",
  },
  {
    name: "Fruitdale School Lofts",
    img: "/images/fruitdale/fruitdale-hero.jpg",
    type: "redevelopment",
    link: "/redevelopment/fruitdale-school-lofts",
  },
  {
    name: "Eiber Village at Garrison Station",
    img: "/images/eiber-village/eiber-village-hero.jpg",
    type: "redevelopment",
    link: "/redevelopment/eiber-village",
  },
  {
    name: "Hanger 2 Lowry",
    img: "/images/hanger2/hanger-2-hero.jpeg",
    type: "redevelopment",
    link: "/redevelopment/hanger-2-lowry",
  },
  {
    name: "Steam Plant Lofts & Patio Homes",
    img: "/images/steam-plant/steam-plant-hero.jpg",
    type: "redevelopment",
    link: "/redevelopment/steam-plant-lofts",
  },
  {
    name: "Steam Plant Row Homes",
    img: "/images/steam-plant-row-homes/steam-plant-row-homes-hero.jpg",
    type: "redevelopment",
    link: "/redevelopment/steam-plant-row-homes",
  },
  {
    name: "Loretto Heights Community Center",
    img: "/images/machebeuf/machebeuf-hero-2.jpg",
    type: "consulting",
    link: "/consulting/loretto-heights-community-center",
  },
  {
    name: "Western Hotel",
    img: "/images/western-hotel/western-hotel-hero.jpg",
    type: "consulting",
    link: "/consulting/western-hotel",
  },
  {
    name: "Lowell School Redevelopment",
    img: "/images/lowell/lowell-hero.jpg",
    type: "consulting",
    link: "/consulting/lowell-school-redevelopment",
  },
  {
    name: "Innovage Headquarters",
    img: "/images/innovage-headquarters/innovage-headquarters-hero.jpg",
    type: "consulting",
    link: "/consulting/innovage-headquarters",
  },
  {
    name: "Courtyard by Marriott Hotel",
    img: "/images/courtyard-by-marriott-hotel/courtyard-by-marriott-hotel-hero.jpg",
    type: "consulting",
    link: "/consulting/courtyard-marriott-hotel",
  },
  {
    name: "Boston Lofts",
    img: "/images/boston-lofts/boston-lofts-hero.jpg",
    type: "consulting",
    link: "/consulting/boston-lofts",
  },
  {
    name: "The Bank Lofts",
    img: "/images/the-bank-lofts/the-bank-lofts-hero.jpg",
    type: "consulting",
    link: "/consulting/bank-lofts",
  },
  {
    name: "Boulder Wastewater Treatment Facility",
    img: "/images/boulder-wastewater-treatment-facility/boulder-wastewater-treatment-facility-hero.jpeg",
    type: "renewable energy",
    link: "/renewable-energy/boulder-wastewater",
  },
  {
    name: "Community Solar",
    img: "/images/community-solar/community-solar-hero.jpg",
    type: "renewable energy",
    link: "/renewable-energy/community-solar",
  },
];
